config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :posts do
    resources :comments
  end
  resources :users
  root 'posts#index'
  get '/users', to: 'users#index'
  get '/about' , to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :text,  presence: true
	belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user,       only: [:destroy, :edit, :update]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @user = current_user
    @post = @user.posts.new(post_params);
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :text))
			redirect_to @post
		else
			render 'edit'
		end
  end

  def destroy
  	@post.destroy
  	redirect_to root_path
  end

private
     def post_params
       params.require(:post).permit(:title, :text)
     end

     def correct_user
       @post = current_user.posts.find_by(id: params[:id])
       if @post.nil?
         flash[:alert] = "Not your post!"
         redirect_to root_path
       end
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users=User.all
	end

	def show
		@user=User.find(params[:id])
		@posts1 = @user.posts
	end


	def edit
		
	end

	def update
	end

	private
     def user_params
       params.require(:user).permit(:email,:name,:profile)
     end
     def find_user
     	@user = User.find_by_email(params[:email])
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
<div class="comment_content">
<p class="comment_name"><strong><%= comment.name %></strong></p>
<p class="comment_body"><%= comment.body %></p>
<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
</div>
<% if user_signed_in? %>
<p>
 <%= link_to 'Delete Comment', [comment.post, comment],
              method: :delete,class: "button",
              data: { confirm: 'Are you sure?' } %>
</p>
<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @post.comments.build ]) do |f| %>
<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Blog</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= favicon_link_tag 'favicon.ico' %>
 <%= csrf_meta_tags %>
</head>
<body>
<div id="sidebar">

<ul>
<li class="category">Website</li>
<li><%= link_to "Articles", root_path %></li>
<li><%= link_to "Users", users_path %></li>
</ul>

<br>
<br>
<br>


<p align ="right">
<% if !user_signed_in? %>
<button class="button"><%= link_to "Sign In", new_user_session_path%></button>
<button class="button"><%= link_to "Sign Up", new_user_registration_path %></button>
<% end %>
</p>
</div>

<div id="main_content">
<div id="header">
<% if current_page?(root_path) %>
<p>All Posts</p>
<% elsif current_page?(about_path) %>
<p>About</p>
<% else %>
<%= link_to "Back to All Posts", root_path %>
<% end %>

<% if user_signed_in? %>
<div class="buttons">
<button class="button"><%= link_to "New Post", new_post_path %></button>
<button class="button"><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></button>
<button class ="button"><%= link_to "Edit your Profile", edit_user_registration_path %></button>
</div>
<% end %>
</div>

<% flash.each do |name, msg| %>
<%= content_tag(:div, msg, class: "alert") %>
<% end %>

<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
<div id="profile_image">
<%= image_tag "profile.jpeg" %>
</div>

<div id="content">
<h1>Hey, I'm Mackenzie Child</h1>
<p>Welcome to week 2 of my 12 Web Apps in 12 Weeks Challenge.</p>
<p>This week I built a blog in Rails 4. You're actually on the demo application right now. Cool stuff, right!.</p>
<p>If you'd like to follow along as I learn more Ruby on Rails, find me on Twitter <a href="http://twitter.com/mackenziechild">@MackenzieChild</a> or on the web at <a href="http://mackenziechild.me">mackenziechild.me</a>, and get my posts and exclusive content in your inbox by signing up for my newsletter <a href="http://eepurl.com/02olT">here</a>.</p>
</div>
</div>

app/views/posts/_form.html.erb
<%= form_with scope: :post, url: posts_path, local: true do |form| %>

<% if @post.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post </h1>

  <%= form_with(model: @post) do |form| %>

  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>

</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class = "post_wrapper">
  <h2 class = "title"><%= link_to post.title, post_path(post) %></h2>
  <p class = "date"><%= post.user.name %></p>
  <p class = "date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post </h1>

  <%= render 'form'%>
</div>

app/views/posts/show.html.erb
<h3 class="title">
 <strong>Title:</strong>
 <%= @post.title %>

</h3>
<p class ="date">
 Submitted <%= time_ago_in_words(@post.created_at) %>Ago
 <% if user_signed_in? %>
 <br>
 <br>
 <strong><%= link_to 'Edit', edit_post_path(@post) %></strong><br>
 <strong><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %></strong>
 <% end %>
</p>
<p class ="body">
   <%= @post.text %>
</p>
<div id="comments">
 	<h2><%= @post.comments.count %> Comments</h2>
 	<%= render @post.comments %>

 	<h3>Add a comment:</h3>
 	<%= render "comments/form" %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class = "post_wrapper">
  <h2 class = "title"><%= link_to user.name, user_path(user) %></h2>
</div>
<% end %>

app/views/users/show.html.erb
<h3 class="title">
 <strong>Email:</strong>
 <%= @user.email %>
 <br>
 <strong>Name:</strong>
 <%= @user.name %>
 <br>
 <strong>Profile:</strong>
 <%= @user.profile %>
 <br>
</h3>
 <% @posts1.each do |post| %>
  <div class = "post_wrapper">
  <h2 class = "title"><%= link_to post.title, post_path(post) %></h2>
  <p class = "date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
</div>
<% end %>